# Generated by Django 4.2.3 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deal_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.BooleanField(default=False)),
                ('bill', models.BooleanField(default=False)),
            ],
        ),
    ]
