# Generated by Django 4.2.3 on 2025-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_printstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='token_printed',
            field=models.BooleanField(default=False),
        ),
    ]
