# Generated by Django 4.2.3 on 2025-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_token_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='printed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
