# Generated by Django 4.2.3 on 2025-07-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_printed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='food_panda_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_panda_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('food_panda', 'Food Panda')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_kitchen', 'In Kitchen'), ('served', 'Served'), ('paid', 'Paid'), ('food_panda', 'Food Panda')], default='pending', max_length=20),
        ),
    ]
