# Generated by Django 4.2.3 on 2025-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_purchaseorder_purchaseorderitem_rawmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Sum of ingredients' cost", max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto‑calculated from recipe', max_digits=10),
        ),
    ]
