# Generated by Django 4.2.3 on 2025-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_waiter_order_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isHomeDelivery',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
