# Generated by Django 4.2.3 on 2025-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_ishomedelivery_alter_waiter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('food_panda', 'Food Panda'), ('walk_in', 'Walk‑in')], max_length=20, null=True),
        ),
    ]
