# Generated by Django 4.2.3 on 2025-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_menuitem_price_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(help_text='E.g. kg, liter, pc', max_length=50),
        ),
    ]
