# Generated by Django 5.2.4 on 2025-08-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('menu', 'MenuItem'), ('deal', 'Deal')], max_length=10)),
                ('source_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_items', to='core.table')),
            ],
            options={
                'unique_together': {('table', 'source_type', 'source_id')},
            },
        ),
    ]
