# Generated by Django 5.2.4 on 2025-08-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tablemenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemenuitem',
            name='printed_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.table')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_sessions', to='core.waiter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tablemenuitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tablemenuitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picked_items', to='core.tablesession'),
        ),
        migrations.AlterUniqueTogether(
            name='tablemenuitem',
            unique_together={('session', 'source_type', 'source_id')},
        ),
        migrations.RemoveField(
            model_name='tablemenuitem',
            name='table',
        ),
    ]
