# Generated by Django 5.2.4 on 2025-08-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tablemenuitem_printed_quantity_tablesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
