# Generated by Django 5.2.4 on 2025-08-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_category_rank_deal_rank_menuitem_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
