# Generated by Django 5.2.4 on 2025-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tablesession_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
