# Generated by Django 5.2.4 on 2025-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_orders',
            field=models.BooleanField(default=True, help_text='If false, this category will be hidden in the order‐taking UI.'),
        ),
    ]
