# Generated by Django 5.2.4 on 2025-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bankaccount_cashflow_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
