# Generated by Django 5.2.4 on 2025-08-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_role_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('security_guard', 'Security Guard'), ('it_manager', 'IT Manager'), ('helper', 'Helper'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
