# Generated by Django 5.2.4 on 2025-08-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='cashflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expense', to='core.cashflow'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash (Restaurant Cash)'), ('bank', 'Bank Account')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('stationery', 'Stationery'), ('maintenance', 'Maintenance'), ('software', 'Software'), ('purchase', 'Purchases/Other Items'), ('other', 'Other')], max_length=20),
        ),
    ]
