# Generated by Django 5.2.4 on 2025-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_expense_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='joined_on',
            field=models.DateField(blank=True, help_text='Staff registry date', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_start',
            field=models.DateField(blank=True, help_text='Salary starts from this date (month-wise)', null=True),
        ),
    ]
