# Generated by Django 5.2.4 on 2025-08-14 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_staff_joined_on_staff_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.CreateModel(
            name='KitchenVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('vtype', models.CharField(choices=[('issue', 'Issue to Kitchen'), ('return', 'Return from Kitchen')], default='issue', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_vouchers', to=settings.AUTH_USER_MODEL)),
                ('handler', models.ForeignKey(blank=True, help_text='Kitchen/Store in-charge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KitchenVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rawmaterial')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_item', to='core.inventorytransaction')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.kitchenvoucher')),
            ],
        ),
        migrations.AddIndex(
            model_name='kitchenvoucher',
            index=models.Index(fields=['vtype', 'date'], name='core_kitche_vtype_bfaa5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchenvoucheritem',
            unique_together={('voucher', 'raw_material')},
        ),
    ]
