# Generated by Django 5.2.4 on 2025-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_inventorytransaction_date_kitchenvoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('jazz cash', 'Jazz Cash'), ('easypaisa', 'Easypaisa'), ('bank', 'Bank'), ('card', 'Card')], max_length=20),
        ),
    ]
