# Generated by Django 5.2.4 on 2025-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
