# Generated by Django 5.2.4 on 2025-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tokensequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('food_panda', 'Food Panda'), ('walk_in', 'Walk-in')], max_length=20, null=True),
        ),
    ]
