# Generated by Django 5.2.4 on 2025-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_tablemenuitem_created_at_tablemenuitem_last_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemenuitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablemenuitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
