# Generated by Django 5.2.4 on 2025-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_tablemenuitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.DateField(db_index=True, unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-service_day'],
            },
        ),
    ]
