# Generated by Django 5.1 on 2025-12-24 10:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tokencounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Kitchen, BBQ Section, Bar', max_length=100, unique=True)),
                ('printer_name', models.CharField(blank=True, help_text='Windows Printer Name (optional)', max_length=200, null=True)),
                ('print_separate_slip', models.BooleanField(default=True, help_text='If True, items for this station print on a separate paper slip.')),
                ('use_separate_sequence', models.BooleanField(default=False, help_text='If True, this station has its own Token #1, #2... independent of Main Kitchen.')),
            ],
        ),
        migrations.AddField(
            model_name='possettings',
            name='start_of_day_time',
            field=models.TimeField(default=datetime.time(6, 0), help_text='The time a new business day starts (e.g., 06:00 AM or 12:00 PM). Token numbers reset at this time.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='theme_color',
            field=models.CharField(default='#ff5722', max_length=7),
        ),
        migrations.AlterField(
            model_name='tokensequence',
            name='business_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name='category',
            name='default_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.printstation'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.printstation'),
        ),
        migrations.AddField(
            model_name='tokensequence',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Null means Global/Main sequence', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.printstation'),
        ),
        migrations.AlterUniqueTogether(
            name='tokensequence',
            unique_together={('business_date', 'station')},
        ),
    ]
