# Generated by Django 5.1 on 2026-01-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_printstation_possettings_start_of_day_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces'), ('doz', 'Dozen'), ('box', 'Box'), ('pack', 'Pack')], help_text='Unit of measurement', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight/quantity of the item', max_digits=10, null=True),
        ),
    ]
